#!/bin/sh
# postinst script for lbweb-admin
#
# see: dh_installdeb(1)
set -e

SYSTEMNAME=proxy3

if ! id -u $SYSTEMNAME > /dev/nul 2>&1; then
	echo asdfasdf
    adduser --system --no-create-home --disabled-login --group $SYSTEMNAME
fi

UID=`id -u $SYSTEMNAME`
GID=`id -g $SYSTEMNAME`

chown $UID:$GID -R /etc/3proxy
chown $UID:$GID /usr/sbin/3proxy


sed -i.bak "s,%SETUID%,$uid,g" /etc/3proxy/main.cfg
sed -i.bak "s,%SETGID%,$gid,g" /etc/3proxy/main.cfg
